# Generated by Django 2.2.1 on 2019-05-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='unique_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
