# Generated by Django 2.2.1 on 2019-05-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_auto_20190514_2124'),
    ]

    operations = [
    ]
