# Generated by Django 2.2.1 on 2019-05-15 05:48

import affiliates.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_auto_20190514_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=affiliates.utils.get_affiliate_qr_code_upload_path),
        ),
    ]
