# Generated by Django 2.2.1 on 2019-05-15 17:48

import affiliates.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_affiliate_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=affiliates.utils.get_picture_upload_path),
        ),
    ]
