# Generated by Django 2.2.1 on 2019-05-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_auto_20190512_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AffiliatePermanentAddress',
            new_name='AffiliateAddress',
        ),
    ]
