# Generated by Django 2.2.1 on 2019-05-15 18:05

import affiliates.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_affiliate_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='profile_pic_thumbnail_url',
            field=models.CharField(blank=True, default='https://d28fujbigzf56k.cloudfront.net/static/img/nopic_small.jpg', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='profile_pic_url',
            field=models.CharField(blank=True, default='https://d28fujbigzf56k.cloudfront.net/static/img/nopic.jpg', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='AffiliatePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=affiliates.utils.get_picture_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=affiliates.utils.get_thumbnail_upload_path)),
                ('is_profile_pic', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='affiliates.Affiliate')),
            ],
        ),
    ]
