# Generated by Django 2.2.1 on 2019-05-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0005_auto_20190512_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='organisation',
        ),
    ]
