# Generated by Django 2.2.1 on 2019-05-12 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0006_remove_affiliate_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='affiliate',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='affiliates.Affiliate'),
            preserve_default=False,
        ),
    ]
