# Generated by Django 2.2.1 on 2019-05-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0006_affiliatebankdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliateoccupationcategory',
            options={'verbose_name_plural': 'Affiliate occupation categories'},
        ),
        migrations.AlterModelOptions(
            name='affiliateorganisationtypecategory',
            options={'verbose_name_plural': 'Affiliate organisation type categories'},
        ),
    ]
