# Generated by Django 2.2.1 on 2019-05-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0007_organisation_affiliate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organisation',
            new_name='AffiliateOrganisation',
        ),
    ]
    atomic = False
