# Generated by Django 2.2.1 on 2019-05-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0007_auto_20190516_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='unique_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
