# Generated by Django 2.2.1 on 2019-05-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0008_auto_20190512_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganisationAddress',
            new_name='AffiliateOrganisationAddress',
        ),
    ]
