# Generated by Django 2.2.1 on 2019-05-19 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0008_auto_20190517_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='house_owner_conversion_commission',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='tenant_conversion_commission',
            field=models.FloatField(default=100),
        ),
        migrations.CreateModel(
            name='AffiliateWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField(default=0)),
                ('debit', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('pending_deposit', models.FloatField(default=0)),
                ('pending_withdrawal', models.FloatField(default=0)),
                ('affiliate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='affiliates.Affiliate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AffiliatePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='affiliates.AffiliateWallet')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateMonthlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('earning', models.FloatField(default=0)),
                ('tenant_conversion_count', models.IntegerField(default=0)),
                ('house_owner_conversion_count', models.IntegerField(default=0)),
                ('start_balance', models.FloatField(default=0)),
                ('end_balance', models.FloatField(default=0)),
                ('affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_reports', to='affiliates.Affiliate')),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
    ]
