# Generated by Django 2.2.1 on 2019-05-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0009_auto_20190519_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatemonthlyreport',
            name='house_owner_conversion_commission',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='affiliatemonthlyreport',
            name='tenant_conversion_commission',
            field=models.FloatField(default=100),
        ),
    ]
