# Generated by Django 2.2.1 on 2019-05-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0010_auto_20190519_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Pending Delivery', 'Pending Delivery'), ('Delivered', 'Delivered')], default='Pending Approval', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode_requests', to='affiliates.Affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeRequestAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('complete_address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('qrcode_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='affiliates.QRCodeRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
