# Generated by Django 2.2.1 on 2019-05-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0011_qrcoderequest_qrcoderequestaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeRequestDeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('complete_address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='qrcoderequest',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='QRCodeRequestAddress',
        ),
        migrations.AddField(
            model_name='qrcoderequestdeliveryaddress',
            name='qrcode_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='affiliates.QRCodeRequest'),
        ),
    ]
