# Generated by Django 2.2.1 on 2019-05-16 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0006_affiliatebankdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('preferred_location', models.TextField(blank=True, null=True)),
                ('expected_rent', models.FloatField(default=0)),
                ('expected_movein_date', models.DateField(blank=True, null=True)),
                ('accomodation_for', models.CharField(blank=True, choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family')], max_length=25, null=True)),
                ('accomodation_type', models.CharField(choices=[('shared', 'Shared rooms'), ('private', 'Private rooms'), ('flat', 'Entire house')], max_length=20)),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_referrals', to='affiliates.Affiliate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseOwnerReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('house_address', models.TextField(blank=True, null=True)),
                ('bhk_count', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_owner_referrals', to='affiliates.Affiliate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
