# Generated by Django 2.2.1 on 2019-05-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseownerreferral',
            name='source',
            field=models.CharField(blank=True, choices=[('Dashboard Form', 'Dashboard Form'), ('Dashboard File Upload', 'Dashboard File Upload'), ('Website Enquiry', 'Website Enquiry'), ('Website Login', 'Website Login')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='houseownerreferral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='houseownerreferral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenantreferral',
            name='source',
            field=models.CharField(blank=True, choices=[('Dashboard Form', 'Dashboard Form'), ('Dashboard File Upload', 'Dashboard File Upload'), ('Website Enquiry', 'Website Enquiry'), ('Website Login', 'Website Login')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenantreferral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantreferral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
