# Generated by Django 2.2.1 on 2019-05-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_auto_20190516_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseownerreferral',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenantreferral',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
