# Generated by Django 2.2.1 on 2019-05-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_auto_20190516_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantreferral',
            name='expected_rent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
