# Generated by Django 2.2.1 on 2019-05-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_auto_20190516_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantreferral',
            name='accomodation_type',
            field=models.CharField(blank=True, choices=[('shared', 'Shared rooms'), ('private', 'Private rooms'), ('flat', 'Entire house')], max_length=20, null=True),
        ),
    ]
