# Generated by Django 2.2.1 on 2019-07-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0007_auto_20190519_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseownerreferral',
            name='lead_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantreferral',
            name='lead_published',
            field=models.BooleanField(default=False),
        ),
    ]
