# Generated by Django 2.2.1 on 2019-08-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0008_auto_20190709_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseownerreferral',
            name='expected_rent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='houseownerreferral',
            name='furnish_type',
            field=models.CharField(blank=True, choices=[('full', 'Fully furnished'), ('semi', 'Semi furnished'), ('nil', 'Unfurnished')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='houseownerreferral',
            name='house_landmark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
