# Generated by Django 2.2.1 on 2019-05-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='updated_on',
            new_name='updated_at',
        ),
    ]
